### ISSUE TITLE
SASL support

### ISSUE THREAD

**Issue by Astaoth** [Kloadut/SSOwat#30]
Hi,

It will be nice if you can add SASL server support for authentications. In this way, for tiny setups or just a few users, we could avoid to have an LDAP in addition of a SASL server.

BR,
Astaoth

**Comment by opi** [comment]
Is this still relevant ? Could you provide any proof-of-concept of SSOwat using SASL server instead of LDAP ?
By now SSOwat is mainly used as YunoHost SSO server which and depends on LDAP. The YunoHost team don't have time to hack on SASL support. I'll close this issue but feel free to re-open it if you have any prototype you want to share.

**Comment by Astaoth** [comment]
I was looking for a loging portal, like SSOwat, in order to use it with other softwares, like SOGo. And I was looking for the SASL support because I am the only user on my server, I don't want to setup a LDAP in order to store only one user. However I started my own project which will fit better my needs (running on apache, additionnal functionnalities, etc).
