### ISSUE TITLE
Unable to use in OpenResty

### ISSUE THREAD

**Issue by dromer** [Kloadut/SSOwat#51]
This week I've been trying to get SSOwat to work in my setup.
For this I needed an hmac function in lua which led me to OpenResty.
( I initially tried this in plain nginx, but this doesn't work due to 'ffi' which is in LuaJIT)

However OpenResty is unable to use the lua-ldap module, or I'm unable to make it work.
What am I doing wrong, or is the readme at fault?

**Comment by Annakan** [comment]
go there [luarocks on openresty](http://openresty.org/#UsingLuaRocks ) and install `luarocks` the latest versions is here `http://keplerproject.github.io/luarocks/releases/` (2.3.0 now)

Then with the installed luarocks (default in `/usr/local/openresty/luajit/bin/luarocks`) install the following modules 
```
lpeg
luafilesystem
luajson
lualdap
luasocket
md5
```

Like this 

```
/usr/local/openresty/luajit/bin/luarocks install luasocket
/usr/local/openresty/luajit/bin/luarocks install luajson
```
etc ...

You might have to install `openldap-devel `(on centos7 , the equivalent one on Ubuntu or whatever your distrib is)

You might encouter other problems because ssowat [is using the worse way of including modules in lua](http://hisham.hm/2014/01/02/how-to-write-lua-modules-in-a-post-module-world/) (and you can read [this](v) and [this](https://blog.separateconcerns.com/2014-01-03-lua-module-policy.html)) and on some configuration I have seen it trip nginx see this to have an hint why **[Lua Variable Scope](https://github.com/openresty/lua-nginx-module#lua-variable-scope)**

**Comment by opi** [comment]
@dromer is this issue still relevant ? (doing some issues triage & cleanup)

**Comment by dromer** [comment]
No I have gotten it to work, thnx :)
